from enum import Enum


class OrderExecutionState(str, Enum):
    IN_FLIGHT = "IN_FLIGHT"
    FILLED = "FILLED"
    REJECTED_BY_BROKER = "REJECTED_BY_BROKER"
    EXECUTION_UNCERTAIN = "EXECUTION_UNCERTAIN"
    CANCELLED = "CANCELLED"


class ExitReason(str, Enum):
    STOP_LOSS = "STOP_LOSS"
    TAKE_PROFIT = "TAKE_PROFIT"
    MANUAL_CLOSE = "MANUAL_CLOSE"
    SIGNAL_INVALIDATION = "SIGNAL_INVALIDATION"
    HARD_KILL_SWITCH = "HARD_KILL_SWITCH"
    TIME_EXPIRATION = "TIME_EXPIRATION"
